### ISSUE TITLE
Плохо работает с less файлами Espresso

### ISSUE THREAD

**Issue by igormorozov** [emmetio/emmet-objc#1]
Такая конструкция срабатывает через раз:

```
.test {
    &__content {
    d:b
    }   
}
```

Раскладывается в

```
.test {
    &__content {
    <d:b></d:b>
    }   
}
```

Причем заметил особенность. bdt - раскладывается в border-top:

Также не работает такого вида конструкция:

```
&:first-child {
        pl
        }
```

**Comment by sergeche** [comment]
Улучшил определение синтаксиса, теперь должно работать.

PS: плагин переехал на новое место https://github.com/emmetio/Emmet.sugar

**Comment by igormorozov** [comment]
Все отлично. Спасибо.
